let testGames = [{
    room: 'A',
    players: [{
        id: '1',
        name: 'Shawn',
        role: 'R',
        ready: true
    }, {
        id: '2',
        name: 'Colin',
        role: 'R',
        ready: false,
    }, {
        id: '3',
        name: 'Eric',
        role: 'R',
        ready: true,
    }, {
        id: '4',
        name: 'Devin',
        role: 'R',
        ready: false,
    }, {
        id: '5',
        name: 'Cameron',
        role: 'R',
        ready: false
    }],
    phase: 'setup',
    score: {
        resistance: 0,
        spies: 0,
    },
    leader: 0,
    proposedTeam: [],
    currentYesVotes: 0,
    currentVotes: 0,
}, {
    room: 'B',
    players: [{
        id: '6',
        name: 'Aragorn',
        role: 'R',
        ready: true
    }, {
        id: '7',
        name: 'Legolas',
        role: 'R',
        ready: true
    }, {
        id: '8',
        name: 'Gimli',
        role: 'S',
        ready: true
    }, {
        id: '9',
        name: 'Merry',
        role: 'R',
        ready: true
    }, {
        id: '10',
        name: 'Pippin',
        role: 'S',
        ready: true
    }, {
        id: '11',
        name: 'Gandalf',
        role: 'R',
        ready: true
    }],
    phase: 'mission-select',
    score: {
        resistance: 0,
        spies: 0,
    },
    leader: 3,
    proposedTeam: [],
    currentYesVotes: 0,
    currentVotes: 0,
}, {
    room: 'C',
    players: [{
        id: '12',
        name: 'Harry',
        role: 'S',
        ready: true
    }, {
        id: '13',
        name: 'Ron',
        role: 'S',
        ready: true
    }, {
        id: '14',
        name: 'Hermione',
        role: 'R',
        ready: true
    }, {
        id: '15',
        name: 'Ginny',
        role: 'S',
        ready: true
    }, {
        id: '16',
        name: 'Luna',
        role: 'R',
        ready: true
    }, {
        id: '17',
        name: 'Cho',
        role: 'R',
        ready: true
    }, {
        id: '18',
        name: 'Neville',
        role: 'R',
        ready: true
    }, ],
    phase: 'mission-vote',
    score: {
        resistance: 0,
        spies: 0,
    },
    leader: 0,
    proposedTeam: ['14', '16', '17'],
    currentYesVotes: 0,
    currentVotes: 0,
}];

module.exports = {testGames};